services:
  db_facturacion:
    image: mysql:8.0
    container_name: db_facturacion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_facturacion
      MYSQL_USER: facturacion
      MYSQL_PASSWORD: facturacion2026
    ports:
      - "3309:3306"
    volumes:
      - db_facturacion_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
   

  api_facturacion:
    build: .
    container_name: api_facturacion
    restart: always
    depends_on:
      db_facturacion:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_HOST: db_facturacion
      DB_USER: facturacion
      DB_PASSWORD: facturacion2026
      DB_NAME: db_facturacion
      DB_PORT: 3306
      JWT_KEY: cambia-esta-clave-por-una-segura
    ports:
      - "3000:3000"

volumes:
  db_facturacion_data: